name: Deploy to shihong.me

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to server
        run: |
          rsync -avz --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude ".gitignore" \
            --exclude "README.md" \
            ./ \
            deploy@shihong.me:/srv/www/shihong.me

      - name: Reload nginx
        run: |
          ssh -o StrictHostKeyChecking=no deploy@shihong.me \
            "sudo -n nginx -t && sudo -n systemctl reload nginx"
